#' Compute surrogate track by randomizing the steps of an observed track
#'
#' Converts a track to a distance/bearing representation, and then
#' reconstructs a new track by randomly perturbing the bearings of
#' each increment, and otpionally, randomly reordering the
#' increments.
#'
#' @title Randomized track
#' @param lonlat a 2-column matrix or dataframe with longitude and
#' latitude of each point
#' @param rotate a 2-element numeric vector giving the lower and
#' upper limits of the random rotation to apply to the randomized
#' track
#' @param reorder should the track steps be randomly reordered?
#' @return A dataframe with columns:
#' * `lon`: the longitude of the randomized track
#' * `lat`: the latitude of the randomized track
#' @export
randomize_track <- function(lonlat,rotate=c(-pi,pi),reorder=FALSE) {
  ## distance and final bearing for each step
  db <- calc_distbearing(lonlat)
  ## Randomize the step order
  if(reorder)
    db <- db[sample.int(nrow(db)),]
  if (!is.null(rotate)) {
    db[,2] <- db[,2]+runif(1,min=min(rotate)/pi*180,max=max(rotate)/pi*180)
  }
  for (k in 2:nrow(lonlat)) {
    lonlat[k,] <- destPoint(lonlat[k-1,],db[k-1,2],db[k-1,1])
  }
  data.frame(lon=lonlat[,1],lat=lonlat[,2])
}


#' Calculate distances in metres and bearing between successive points along track
#'
#' This is an internal function used by [randomize_track()]
#' @title Distance and Bearing
#' @param lonlat a 2-column matrix or dataframe with longitude and
#' latitude of each point
#' @return A dataframe with columns:
#' * `lon`: the longitude of the randomized track
#' * `lat`: the latitude of the randomized track
calc_distbearing <- function(lonlat) {
  nr <- nrow(lonlat)
  dst <- distVincentySphere(lonlat[-nr,],lonlat[-1,])
  ## Why is this the final bearing??
  brg <- finalBearing(lonlat[-nr,],lonlat[-1,])
  data.frame(distance=dst,bearing=brg)
}



#' Fit first-order vector-autoregressive model to track
#'
#' This function fits the vector AR(1) model used as the `model` argument to [surrogateAR()]
#'
#' @title VAR(1) track model
#' @param lonlat a 2-column matrix or dataframe with longitude and
#' latitude of each point
#' @return An object of class "ar"
#' @seealso [ar()], [surrogateAR()]
#' @export
surrogateARModel <- function(lonlat) {

    ## Fixed at 1st order model for now. Might allow this as a param,
    ## but needs surrogate_arsimulate code updated to handle higher
    ## model orders first
    model.order <- 1

    ## Calculate distance increments dx, dy for each time step
    nr <- nrow(lonlat)
    lonlat <- lonlat[, 1:2, drop = FALSE]
    dx <- distVincentyEllipsoid(cbind(lonlat[-1, 1], lonlat[-nr, 2]), lonlat[-nr, ]) * sign(lonlat[-1, 1] - lonlat[-nr, 1])
    ## eastwards movement has positive sign

    ## the sign of dx will be wrong when the track crosses the date line
    ##  noting that we can have a track segment going from positive longitude (say 179E) to negative longitude (179W) crossing the date line, but also a segment crossing the zero line (1E to 1W) - the latter will be correct
    tempdx <- lonlat[-nr, 1] - lonlat[-1, 1] ## x difference on given coords
    tempdx2 <- lonlat[-nr, 1] - (lonlat[-1, 1] + 180) ## lon difference but with starting point shifted 180 degrees eastwards
    tempdx3 <- lonlat[-nr, 1] + 180 - lonlat[-1, 1] ## lon difference but with ending point shifted 180 degrees eastwards
    idx <- which((lonlat[-nr, 1] > 0 & lonlat[-1, 1] < 0 & abs(tempdx2) < abs(tempdx)) | (lonlat[-nr, 1] < 0 & lonlat[-1, 1] > 0 & abs(tempdx3) < abs(tempdx)))
    dx[idx] <- -dx[idx] ## change the sign of these

    dy <- distVincentyEllipsoid(cbind(lonlat[-nr, 1], lonlat[-1, 2]), lonlat[-nr, ]) * sign(lonlat[-1, 2] - lonlat[-nr, 2])
    ## northwards movement has positive sign

    ## Fit AR1 to distance increments
    dxdy <- data.frame(dx = dx, dy = dy)
    ar(dxdy, order.max = model.order, aic = FALSE)
}


#' Generate new tracks from a VAR(1)
#'
#' Given a fitted VAR(1) model and a template track, this function
#' generates a new track of the same length that coincides with the
#' template at the start point and optionally other specified points
#' along the track.
#'
#' The template track must be supplied as a matrix representing a
#' sequence of locations where each row is a location and the columns
#' represent longitude and latitude.  The locations must be
#' equispaced in time (e.g. the "p" location types from a fitted crawl or aniMotum model.
#'
#' The model object is generated by [surrogateARModel()] from a
#' filtered, iunterpolated track.  This fits a VAR(1) model to the
#' increments in longitude and latitude.
#'
#' Locations from the template track can be marked as fixed with the
#' `fixed` argument. In the current implementation the first
#' location must always be fixed.
#'
#' Additional constraints can be placed on the path by rejection
#' sampling through the function `point.check`.  This function
#' must accept a state and return a boolean indicating whether the
#' point is acceptable.  For example, the track can be constrained to
#' the ocean by supplying a `point.check` function that compares
#' the state to a land mask and returns `FALSE` for states
#' corresponding to locations that fall on land.
#'
#' @title VAR bridge sampler
#' @param model a model generated with [surrogateARModel()]
#' @param ts the times at which the track is sampled
#' @param xs the template sequence of states
#' @param fixed a logical vector indicating which locations in the
#' template path are to be held fixed.
#' @param point.check function that accepts a state and
#' returns boolean indicating whether the state is acceptable.
#' @param random.rotation the upper and lower limits (radians) of the
#' rotation applied to the VAR(1) model.
#' @param partial if `TRUE`, a partial track is returned if the
#' sampling fails.
#' @return An array of states the define the simulated path.
#' @export
surrogateAR <- function(model, xs, ts = seq_len(nrow(xs)), fixed = rep(c(TRUE, FALSE, TRUE), c(1, nrow(xs)-2, 1)), point.check = function(tm, pt) TRUE, random.rotation = c(-pi, pi), partial = FALSE) {

    if (is.data.frame(xs)) xs <- as.matrix(xs)

    xs <- unname(xs[, 1:2, drop = FALSE])
    n <- nrow(xs)

    ## Construct that fit that would have been obtained had the data been
    ## rotated with rotation matrix R.
    rotateVAR1 <- function(model, theta) {
        if (abs(theta) > 1e-09) {
            nms <- names(model$x.mean)
            R <- matrix(c(cos(theta), sin(theta), -sin(theta), cos(theta)), 2, 2)
            model$ar[1, , ] <- R %*% model$ar[1, , ] %*% t(R)
            model$var.pred <- R %*% model$var.pred %*% t(R)
            model$x.mean <- model$x.mean %*% t(R)
            names(model$x.mean) <- nms
        }
        model
    }

    ## Simulate forward from k0.  Returns the index of the last fixed point reached if an acceptable next candidate cannot be found.
    sample <- function(k0, A, U, mu) {
        z <- double(2)
        for (i in 1:100) z <- drop(A %*% z) + drop(rnorm(2) %*% U)

        ## Simulate forward from k0
        x <- xs[k0, ]
        k <- k0 + 1

        ## Find remaining fixed points
        kfixed <- if(k <= n) (k:n)[fixed[k:n]] else integer(0)

        while (k <= n) {
            if (fixed[k]) {
                ## Skip fixed points
                while (k <= n && fixed[k]) {
                    x <- xs[(k0 <- k), ]
                    k <- k + 1L
                }
                ## Find any remaining fixed points
                kfixed <- if (k <= n) (k:n)[fixed[k:n]] else integer(0)
                ## Re-initialize z
                z <- double(2)
                for (i in 1:100) z <- drop(A %*% z) + drop(rnorm(2) %*% U)
            } else {
                ## Try at most 100 new candidates
                for (r in 1:100) {
                    ## Trial z - simulate from centred VAR(1) model
                    z1 <- drop(A %*% z) + drop(rnorm(2) %*% U)
                    ## Trial x - take step in lon then lat.
                    x1 <- as.vector(destPoint(destPoint(x, 90, z1[1] + mu[1]), 0, z1[2] + mu[2]))
                    ## Nudge - this seems a little aggressive
                    if (length(kfixed)) {
                        this_nudge <- xs[kfixed[1], ] - x1
                        this_nudge[1] <- angle_normalise(this_nudge[1] / 180 * pi) / pi * 180
                        x1 <- x1 + (this_nudge) / (kfixed[1] - k + 1L)
                    }
                    ## Test current candidate
                    if (point.check(ts[k], x1)) {
                        ## Accept candidate
                        z <- z1
                        xs[k, ] <<- (x <- x1)
                        k <- k + 1L
                        break
                    } else {
                        ## On failure return last fixed point
                        if (r == 100L) return(k0)
                    }
                }
            }
        }
        ## Return n+1 on success
        return(n + 1L)
    }

    ## Try 100 rotations of the model
    for (roti in 1:100) {
        theta <- if (is.null(random.rotation)) 0 else runif(1, random.rotation[1], random.rotation[2])
        model0 <- rotateVAR1(model, theta)
        A <- unname(model0$ar[1, , ])
        U <- chol(unname(model0$var.pred))
        mu <- as.vector(model0$x.mean)
        k <- 1L
        fails <- 0
        for (i in 1:50) {
            knew <- if (i < 25) sample(k, A, U, mu) else sample(1, A, U, mu)
            if (knew == k) fails <- fails + 1L ## failed to find valid new point
            k <- knew
            if(k > n) return(list(xs = xs, ts = ts))
        }
        if (fails == 50) warning("Failed to find acceptable point at step ", k, ". If surrogateAR fails to return a track, this might indicate a location from which it is not possible to step to another, valid location.")
    }
    ## Return partial track or NULL
    if (partial) {
        xs[k:n, ] <- NA
        list(xs = xs, ts = ts)
    }
}




#' Generate Transition and Covariance Matrices for a simple Crawl Model
#'
#' Generates the transition and covariance matrices of the state
#' space model for time increment `dt`, corresponding to a
#' fitted crawl model with no drift and no covariates.
#'
#' Currently no polar adjustment is made.
#'
#' The matrices are generated assuming the state variables are stored
#' as a vector in the order longitude mu and nu then latitude mu and
#' nu.  The parametrization is defined as in the crawl source not the
#' paper, which differs by a factor of \eqn{\beta^{2}} in the
#' definition of \eqn{\sigma^{2}}.
#'
#' @title Crawl Movement Model
#' @param fit a fitted crawl object
#' @param dt the fixed time increment
#' @return A list containing
#' * `A`: the transition matrix
#' * `Q`: the covariance matrix
#' * `dt`: the time increment
#' @export
surrogateCrawlModel <- function(fit, dt) {
    warning("surrogateCrawlModel was developed with crawl package version 1, it has not been tested with v2")
    ## Components of the transition and covariance matrices
    a <- function(beta) (1 - exp(-beta * dt)) / beta
    b <- function(beta) exp(-beta * dt)
    v11 <- function(sigma, beta) (sigma)^2 * (dt-2 * a(beta)+a(2 * beta))
    v12 <- function(sigma, beta) (sigma)^2 * (1-2 * b(beta)+b(2 * beta))/2
    v22 <- function(sigma, beta) (beta * sigma)^2 * a(2 * beta)

    ## This matches the code but differs from the paper.
    n.err <- fit$n.errX+fit$n.errY
    sigma1 <- sigma2 <- exp(fit$par[n.err+1])
    beta1 <- beta2 <- exp(fit$par[n.err+2])

    ## Transition and covariance matrices
    A <- matrix(c(1, 0, a(beta1), 0,
                  0, 1, 0, a(beta2),
                  0, 0, b(beta1), 0,
                  0, 0, 0, b(beta2)), 4, 4, byrow = TRUE)
    Q <- matrix(c(v11(sigma1, beta1), 0, v12(sigma1, beta1), 0,
                  0, v11(sigma2, beta2), 0, v12(sigma2, beta2),
                  v12(sigma1, beta1), 0, v22(sigma1, beta1), 0,
                  0, v12(sigma2, beta2), 0, v22(sigma2, beta2)), 4, 4, byrow = TRUE)
    list(A = A, Q = Q, dt = dt)
}

#' Generate new tracks from a Crawl model
#'
#' Given a fitted crawl model and a template track, this function
#' generates a new track of the same length that coincides with the
#' template at the start point and optionally other specified points
#' along the track.
#'
#' The template track must be supplied as a matrix representing a
#' sequence of states where each row is a state and each column a
#' state variable.
#' The states must be equispaced in time (e.g. the "p" location types from a fitted crawl or aniMotum model.
#'
#' The crawl model object is generated by [surrogateCrawlModel()] from a
#' fitted crawl model.
#'
#' Locations from the template track can be marked as fixed with the
#' `fixed` argument. In the current implementation the first
#' location must always be fixed.
#'
#' Additional constraints can be placed on the path by rejection
#' sampling through the function `point.check`.  This function
#' must accept a state and return a boolean indicating whether the
#' point is acceptable.  For example, the track can be constrained to
#' the ocean by supplying a `point.check` function that compares
#' the state to a land mask and returns `FALSE` for states
#' corresponding to locations that fall on land.
#'
#' @title Regressive bridge sampler
#' @param model a list with the transition and covariance matrices
#' corresponding to the fitted movement model.
#' @param xs the template sequence of states
#' @param ts the times at which the track is sampled
#' @param fixed a logical vector indicating which locations in the
#' template path are to be held fixed.
#' @param point.check function that accepts a state and returns `TRUE` or `FALSE` indicating whether the state is acceptable.
#' @param Verr error covariance for fixed points.
#' @param partial if `TRUE`, a partial track is returned if the
#' sampling fails.
#' @return An array of states the define the simulated path.
#' @export
surrogateCrawl <- function(model, xs, ts = 1:nrow(xs),
                           fixed = rep(c(TRUE, FALSE, TRUE), c(1, nrow(xs) - 2, 1)),
                           point.check = function(tm, pt) TRUE,
                           Verr = diag(c(.0001, .0001, 0.1, 0.1)),
                           partial = FALSE) {

    warning("surrogateCrawlModel was developed with crawl package version 1, it has not been tested with v2")
    ## Extract model matrices
    A <- model$A
    Q <- model$Q
    QI <- solve(Q)

    ## Enforce fixed first state
    fixed[1] <- TRUE

    xs <- unname(xs)
    n <- nrow(xs)

    ## Priors
    ms <- xs
    Ps <- array(0, c(nrow(Q), ncol(Q), n))

    ## Forward pass - generate priors from movement model
    for (k in 1:n)
        if (fixed[k]) {
            ms[k, 3:4] <- 0
            Ps[, , k] <- Verr
        } else {
            ms[k, ] <- A %*% ms[k - 1, ]
            Ps[, , k] <- A %*% Ps[, , k - 1] %*% t(A) + Q
        }

    ## Reverse pass - recursively sample by Bayesian regression,
    ## starting from x[k0,]
    sample <- function(k0) {
        x <- ms[k0, ] + drop(rnorm(nrow(Verr)) %*% chol(Ps[, , k0]))
        xs[k0, ] <<- x
        for (k in (k0 - 1):1) {
            P <- Ps[, , k]
            PI <- solve(P)
            b <- PI %*% ms[k, ] + t(A) %*% QI %*% x
            ##b <- PI%*%ms[k,]+t(x%*%QI%*%A)
            ## Sample from N(V^{1} b, V^{-1})
            R <- chol(t(A) %*% QI %*% A + PI)
            ## point.check/rejection loop
            for (r in 1:100) {
                x <- drop(backsolve(R, backsolve(R, b, transpose = TRUE) + rnorm(length(b))))
                if (fixed[k] || point.check(ts[k], x[1:2])) break
                ## If fail, return last fixed point
                if(r == 100) return(k0)
            }
            xs[k, ] <<- x

            ## Allow discontinuity at a fixed point
            if (fixed[k]) {
                x <- ms[k, ] + drop(rnorm(nrow(Verr)) %*% chol(Ps[, , k]))
                k0 <- k
            }
        }
        ## On success, return 0
        0
    }

    k <- n
    for (i in 1:50) {
        k <- if (i < 25) sample(k) else sample(n)
        if (k == 0) return(list(xs = xs, ts = ts))
    }
    NULL
}

angle_normalise <- function(x) { (x + pi) %% (2 * pi) - pi } ## normalize angle to range [-pi,pi)
